Added setup.py for deployment to pypi, install twine and push it to PyPI
yashshah1/abuu pull request #7
Opened 2020-10-02 14:20 UTC by abhirambsn

2020-10-02 14:21 UTC, abhirambsn commented
> _No description provided._

Added the required setup.py file for pypi deployment, kindly edit details according to you (eg. email, name of package, etc.)

Regards,
Abhiram BSN

2020-10-02 16:10 UTC, yashshah1 commented
Hi, This is amazing work, Thank you so much. However, is it possible for you to make it a little more configurable? The packages has a entry `utils.pandas`. Is there a way to not have that change every time we add a folder to the package?

For example, now there are 2 other folders. Is adding only `utils` not enough?

2020-10-02 16:11 UTC, yashshah1 commented
@abhirambsn Hi, This is amazing work, Thank you so much. However, is it possible for you to make it a little more configurable? The packages has an entry `utils.pandas`. Is there a way to not have that change every time we add a folder to the package?

For example, now there are 2 other folders. Is adding only `utils` not enough?

2020-10-02 16:14 UTC, yashshah1 commented on abuu/setup.py
> +README = (HERE / "../README.md").read_text()
Do we need "../"?

2020-10-02 16:15 UTC, abhirambsn commented
> @abhirambsn Hi, This is amazing work, Thank you so much. However, is it possible for you to make it a little more configurable? The packages has an entry `utils.pandas`. Is there a way to not have that change every time we add a folder to the package?
> 
> For example, now there are 2 other folders. Is adding only `utils` not enough?

Actually you can add the folders to the packages list like if you add tools folder then you can add the folder name after the utils folder

2020-10-02 16:19 UTC, yashshah1 commented
But that would require me to keep adding to the list after every folder is added, can we do without it?
I took a look at [this](https://github.com/abhishekkrthakur/wtfml/blob/master/setup.py) and he does something with `find_packages()` can we use that?

2020-10-02 18:22 UTC, abhirambsn commented on abuu/setup.py
> +README = (HERE / "../README.md").read_text()
Yes, because your markdown is one directory above in repository root where as setup.py is in the aaub folder inside the repo
so that's why

2020-10-02 18:36 UTC, abhirambsn commented
Actually in the find_packages() function you need to specify the directory of the libraries, by default it searches in the current directory, but if in near future you want a nested package inside your utils directory then it will create issues, so thats why I went with this method

2020-10-03 10:39 UTC, yashshah1 commented
Hi, so two things:
1) Why can't we move setup.py to the root folder? If done like that, we would lose the need of adding a `../` to the path and
2) using `find_packages()` without any params would also work given that we only need to export `abuu` which is a directory in the same path that setup.py lives. Also, `abuu/__init__.py` exists so I'm assuming any doc/examples folder I decide to add later won't be exported along side given that we won't have a `__init__.py` file in that folder

2020-10-03 11:13 UTC, abhirambsn commented
Then you need to add an __init__.py to the repository root

2020-10-03 11:14 UTC, abhirambsn commented
If you say I will take care of that

2020-10-03 17:03 UTC, yashshah1 commented
Are you sure, a lot of projects out there have a directory with the name of the package inside the repo. See [this](https://github.com/abhishekkrthakur/wtfml) and [this](https://github.com/rliebz/whoswho).

But even if that is the case, I prefer having the setup.py outside of where the code lives, given that it isn't doing any logic, but just the setting up of the code.

2020-10-03 18:02 UTC, abhirambsn commented
So you tell me what should I do, should I modify the setup.py or should I leave it as it is, see, If you add any new package inside utils directory and add that to utils/_ _init_ _.py it will be automatically added by my version of setup.py, if you add any folder outside of utils directory then you need to add the directory name, so you tell me what should be my further actions on this issue

2020-10-03 18:05 UTC, yashshah1 commented
I've refactored to remove the utils directory. So now I just have one directory, inside which all the folders live.
So ideally, get the setup.py to the root of this repository, and change the package list to have only `[abuu]` or use `find_packages()`

2020-10-03 18:19 UTC, abhirambsn commented
I have modified the setup.py, if you face any problems comment me

2020-10-03 18:28 UTC, yashshah1 reviewed
Just this one change. Else it lgtm

2020-10-03 18:28 UTC, yashshah1 commented on setup.py
>      install_requires=["pandas"],
```suggestion
    install_requires=[
    	"pandas>=1.0.0",
    	"scikit-learn>=0.22.1"
    ],
```

2020-10-03 19:23 UTC, yashshah1 requested changes

2020-10-03 19:23 UTC, yashshah1 commented on setup.py
> +    },
```suggestion
```
Considering this doesn't ship with a CLI, this isn't needed right?

2020-10-03 19:23 UTC, yashshah1 commented on setup.py
> +    description="ABUU - Another Bunch of Uselessfull Utils",
```suggestion
    description="ABUU - Another Bunch of Usefull Utils",
```
:P

2020-10-03 19:23 UTC, yashshah1 commented on setup.py
> +    version="1.0.0",
```suggestion
    version=abuu.__version__,
```

And add `import abuu` above

2020-10-03 19:23 UTC, yashshah1 commented on setup.py
> +    version="1.0.0",
I've added the versioning in abuu/__init__.py just a few minutes ago, so you might have to pull to see it take effect.

2020-10-04 05:25 UTC, merged

2020-10-04 05:26 UTC, yashshah1 commented
Thank you!

2020-10-04 06:08 UTC, abhirambsn commented
> Thank you!

Mention not, it was fun actually